debian instalation updated

diff --git a/debianinstallation b/debianinstallation
--- a/debianinstallation
+++ b/debianinstallation
@@ -6,9 +6,9 @@ currentVersion="2.1.2"
 declare -a tools=(cheat cipher covidinfo crypt cryptocurrency geo gif googler ipinfo jukebox lyrics meme movie news pwned qrify shareterminal shodan shorturl termux-snippets todo transfer weather)
 prefix="/usr/bin"
 
-rootCheck()
-{
-}
+# rootCheck()
+# {
+# }
 
 
 installationEnd()
@@ -26,21 +26,21 @@ installationEnd()
 
 installOneByOne()
 {
-        echo "___________________________________________"
-        echo -n "Installing $1"
+  echo "___________________________________________"
+  echo -n "Installing $1"
                 if [[ $1 == "weather" ]]; then
                   cd $1 || return 1
                   chmod a+x $1
-                  cp $1 $prefix > /dev/null 2>&1 || { echo "Failure"; echo "Error copying file, try running install script again"; exit 1; }
+      cp $1 $prefix > /dev/null 2>&1 || { echo "Failure"; echo "Error copying file, try running install script again"; exit 1; }
                   echo -e "\n✔Success"
                   cd ..; installationEnd ; exit 0 || return
                 elif [[ $1 == "termux-snippets" ]]; then
-                        #cd .. || return 1
-                        chmod a+x $1
-                        cp $1 $prefix > /dev/null 2>&1 || { echo "Failure"; echo "Error copying file, try running install script again"; exit 1; }
+      #cd .. || return 1
+      chmod a+x $1
+      cp $1 $prefix > /dev/null 2>&1 || { echo "Failure"; echo "Error copying file, try running install script again"; exit 1; }
                       echo -e "\n✔Success"
-                      #cd installation
-                else
+          #cd installation
+                else 
                   cd $1 || return 1
                   chmod a+x $1
                   cp $1 $prefix > /dev/null 2>&1 || { echo "Failure"; echo "Error copying file, try running install script again"; exit 1; }
@@ -84,7 +84,7 @@ singleInstall()
       installOneByOne $tool || exit 1
     done
   fi
-
+  
 if [[ $# == 0 ]]; then
   for tool in "${tools[@]}"; do
     installOneByOne $tool || exit 1
