recent update

diff --git a/install b/install
--- a/install
+++ b/install
@@ -54,9 +54,9 @@ askInstall()
 	}
 
 	while true; do
-	  exec 3>&1
-	  selection=$(dialog \
-	    --backtitle "From @hakxcore(https://github.com/hakxcore)" \
+		exec 3>&1
+		selection=$(dialog \
+		--backtitle "From @hakxcore(https://github.com/hakxcore)" \
 	    --title "termux-snippets" \
 	    --clear \
 	    --cancel-label "Exit" \
@@ -64,21 +64,21 @@ askInstall()
 	    	"1" "Termux" \
 			"2" "Debian"
 	    2>&1 1>&3)
-	  exit_status=$?
-	  exec 3>&-
-	  ##handle termination error 
-	  case $exit_status in
-	    $DIALOG_CANCEL)
-	      clear
-	      echo "installation terminated."
-	      exit
-	      ;;
-	    $DIALOG_ESC)
-	      clear
-	      echo "installation aborted." >&2
-	      exit 1
-	      ;;
-	  esac
+	  	exit_status=$?
+	  	exec 3>&-
+	  	##handle termination error 
+	  	case $exit_status in
+		  	$DIALOG_CANCEL)
+		  		clear
+		      	echo "installation terminated."
+		      	exit
+		      	;;
+		    $DIALOG_ESC)
+		      	clear
+		      	echo "installation aborted." >&2
+		      	exit 1
+		      	;;
+	  	esac
 	  
 	  ##Operating system Selection 
 	  case $selection in
@@ -99,16 +99,16 @@ askInstall()
 			    exit_statuss=$?
 			    ##Main programme termination error handle
 			    case $exit_statuss in
-			    $DIALOG_CANCEL)
-			      clear
-			      echo "Installation terminated."
-			      exit
-			      ;;
-			    $DIALOG_ESC)
-			      clear
-			      echo "Installation aborted." >&2
-			      exit 1
-			      ;;
+				    $DIALOG_CANCEL)
+				      clear
+				      echo "Installation terminated."
+				      exit
+				      ;;
+				    $DIALOG_ESC)
+				      clear
+				      echo "Installation aborted." >&2
+				      exit 1
+				      ;;
 			  	esac
 
 			  	##Installation on termux
