New modification added

diff --git a/installation b/installation
--- a/installation
+++ b/installation
@@ -4,11 +4,18 @@
 currentVersion="2.1.2"
 
 declare -a tools=(cheat cipher covidinfo crypt cryptocurrency geo gif googler ipinfo jukebox lyrics meme movie news pwned qrify shareterminal shodan shorturl termux-snippets todo transfer weather)
-prefix="/usr/bin"
 
-# rootCheck()
-# {
-# }
+##Platform Check
+distr_name=$1
+if [ "$distr_name" == "Android" ]; then
+  platform="Termux"
+  showError="Try running install script again."
+  prefix="/data/data/com.termux/files/"
+  else
+    platform="Debian"
+    showError="Try running install script again with root privileges."
+    prefix=""
+fi
 
 
 installationEnd()
@@ -24,26 +31,26 @@ installationEnd()
   echo  "https://github.com/hakxcore/Termux-snippets"
 }
 
-installOneByOne()
+installation()
 {
   echo "___________________________________________"
-  echo -n "Installing $1"
+  echo -n "> Installing $1"
                 if [[ $1 == "weather" ]]; then
                   cd $1 || return 1
                   chmod a+x $1
-      cp $1 $prefix > /dev/null 2>&1 || { echo "Failure"; echo "Error copying file, try running install script again with root(sudo) privileges."; exit 1; }
+      cp $1 $prefix/usr/bin > /dev/null 2>&1 || { echo -e "\n✘ Failure"; echo -e "\nError: $showError"; exit 1; }
                   echo -e "\n✔Success"
                   cd ..; installationEnd ; exit 0 || return
                 elif [[ $1 == "termux-snippets" ]]; then
       #cd .. || return 1
       chmod a+x $1
-      cp $1 $prefix > /dev/null 2>&1 || { echo "Failure"; echo "Error copying file, try running install script again with root(sudo) privileges."; exit 1; }
+      cp $1 $prefix/usr/bin > /dev/null 2>&1 || { echo -e "\n✘ Failure"; echo -e "\nError: $showError"; exit 1; }
                       echo -e "\n✔Success"
           #cd installation
                 else 
                   cd $1 || return 1
                   chmod a+x $1
-                  cp $1 $prefix > /dev/null 2>&1 || { echo "Failure"; echo "Error copying file, try running install script again with root(sudo) privileges."; exit 1; }
+                  cp $1 $prefix/usr/bin > /dev/null 2>&1 || { echo -e "\n✘ Failure"; echo -e "\nError: $showError"; exit 1; }
                   echo -e "\n✔Success"
                   cd .. || return 1
                 fi
@@ -52,12 +59,12 @@ installOneByOne()
 
 updateTool()
 {
-  if [[ -f  $prefix/$1 ]]; then
+  if [[ -f  $prefix/usr/bin/$1 ]]; then
     cd $1 || return 1
     git pull origin
-    echo -n "Installing $BLUE$1$RESETBG: "
+    echo -n "> Installing $BLUE$1$RESETBG "
     chmod a+x $1
-    cp $1 $prefix > /dev/null 2>&1 || { echo "Failure"; echo "Error copying file, try running install script again with root(sudo) privileges."; exit 1; }
+    cp $1 $prefix/usr/bin > /dev/null 2>&1 || { echo -e "\n✘ Failure"; echo -e "\nError: $showError"; exit 1; }
     echo ""$GREEN"Success$RESETBG"
     cd ..; installationEnd || return 1
   fi
@@ -67,30 +74,30 @@ updateTool()
 singleInstall()
 {
   cd $1 || exit 1
-  echo -n "Installing $BLUE$1$RESETBG: "
+  echo -n "> Installing $BLUE$1$RESETBG "
   chmod a+x $1
-  cp $1 $prefix > /dev/null 2>&1 || { echo "Failure"; echo "Error copying file, try running install script again with root(sudo) privileges."; exit 1; }
-  echo ""$GREEN"Success$RESETBG"
+  cp $1 $prefix/usr/bin > /dev/null 2>&1 || { echo -e "\n✘ Failure"; echo -e "\nError: $showError"; exit 1; }
+  echo ""$GREEN"  Success$RESETBG"
   cd ..; installationEnd || exit 1
 }
 
 ##Driver
   if [[ $2 == "all" ]];then
     for tool in "${tools[@]}"; do
-      installOneByOne $tool || exit 1
+      installation $tool || exit 1
     done
   else
     for tool in "${@:2}"; do
-      installOneByOne $tool || exit 1
+      installation $tool || exit 1
     done
   fi
   
 if [[ $# == 0 ]]; then
   for tool in "${tools[@]}"; do
-    installOneByOne $tool || exit 1
+    installation $tool || exit 1
   done
 elif [[ $1 == "update" ]]; then
-  echo "Updating scripts..."
+  echo "> Updating scripts..."
   for tool in "${tools[@]}"; do
     updateTool $tool || exit 1
   done
@@ -98,8 +105,8 @@ elif [[ $1 == "update" ]]; then
 
   if [[ $1 == "all" ]]; then
   for tool in "${tools[@]}"; do
-    installOneByOne $tool || exit 1
+    installation $tool || exit 1
   done
 else
-  installOneByOne $1 || exit 1
+  installation $1 || exit 1
 fi
diff --git a/termux-snippets b/termux-snippets
--- a/termux-snippets
+++ b/termux-snippets
@@ -56,7 +56,7 @@ grablatestversion()
 
 checkInternet()
 {
-  httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
+  httpGet github.com > /dev/null 2>&1 || { echo ""$RED"Error: "$GREEN"no active internet connection$RESETBG" >&2; return 1; } # query github with a get request
 }
 
 header()
@@ -87,7 +87,6 @@ echo ""
   printf "\t\t     $BLUE%s$RESETBG\n" "$title"
   printf "\t%s\t%s\n" "$latestver" "$installver"
 }
-
 
 toolMenu()
 {
@@ -190,12 +189,12 @@ installationcheck()
   validTools=()
   for tool in "${tools[@]}"; do
     if [ -e "$prefix/usr/bin/$tool" ]; then
-      check=""$GREEN"Tools Installed Successfully.$RESETBG"
-      state="$GREEN✔$RESETBG";
+      check="$BLUE>$GREEN Snippets Installed Successfully.$RESETBG"
+      state="["$GREEN"✔"$RESETBG"]";
       start=28;
       validTools+=($tool);
     else state="$RED✘$RESETBG"; start=28;
-   	  check=""$REDBG"Warning:$RESETBG "$ORANGE"Tools doesn't installed Correctly, Please try Install again.$RESETBG"
+   	  check=""$REDBG"Warning:$RESETBG "$ORANGE"Snippets doesn't installed Correctly, Please try Install again.$RESETBG"
 	fi
       if $1; then
         echo -n -e "\t\t$BLUE$tool$RESETBG"
