weather to find exact weather report of your location or your specified location use "weather -h" for more information

diff --git a/weather/weather b/weather/weather
--- a/weather/weather
+++ b/weather/weather
@@ -1,14 +1,13 @@
 #!/usr/bin/env bash
-# Author: Alexander Epstein https://github.com/alexanderepstein
-# Modified for Termux by: Hakxcore https://github.com/hakxcore
+# Inspired by: Alexander Epstein https://github.com/alexanderepstein
+# Author: Hakxcore https://github.com/hakxcore
 
-currentVersion="2.1.0" #This version variable should not have a v but should contain all other characters ex Github release tag is v1.2.4 currentVersion is 1.2.4
+currentVersion="2.1.0" 
 LANG="${LANG:-en}"
 locale=$(echo $LANG | cut -c1-2)
 unset configuredClient
 if [[ $(echo $locale | grep -Eo "[a-z A-Z]*" | wc -c) != 3 ]]; then locale="en"; fi
 
-## This function determines which http get tool the system has installed and returns an error if there isnt one
 getConfiguredClient()
 {
   if command -v curl &>/dev/null; then
@@ -25,7 +24,6 @@ getConfiguredClient()
   fi
 }
 
-## Allows to call the users configured client without if statements everywhere
 httpGet()
 {
   case "$configuredClient" in
@@ -66,9 +64,9 @@ checkInternet()
 
 update()
 {
-  repositoryName="Termux-snippets" #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="hakxcore" #username that hosts the repostiory ex. alexanderepstein
-  nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
+  repositoryName="Termux-snippets" 
+  githubUserName="hakxcore"
+  nameOfInstallFile="install" 
   latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
 
   if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
@@ -84,7 +82,7 @@ update()
       read -r answer
       if [[ "$answer" == [Yy] ]]; then
         cd ~ || { echo 'Update Failed'; exit 1; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update again"; exit 1; } ; fi
         echo -n "Downloading latest version of: $repositoryName."
         git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .TSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
         while [ ! -f .TSnippetsHiddenFile ]; do { echo -n "."; sleep 2; };done
@@ -92,10 +90,10 @@ update()
         echo "Success!"
         cd $repositoryName || { echo 'Update Failed'; exit 1; }
         git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
-        chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
-        ./$nameOfInstallFile "update" || exit 1
+
+	./$nameOfInstallFile "update" || exit 1
         cd ..
-        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory again"; exit 1; }
       else
         exit 1
       fi
@@ -143,8 +141,8 @@ while getopts "uvh" opt; do
     v)  echo "Version $currentVersion"
         exit 0
         ;;
-    u)  checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
-        update || exit 1
+    u)  checkInternet || exit 1 
+	    update || exit 1
         exit 0
         ;;
     :)  echo "Option -$OPTARG requires an argument." >&2
